randommer:
  api-key: ${RANDOMMER_API_KEY}

---

spring:
  config:
    activate:
      on-profile: "default"
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL} # jdbc:mysql://localhost:13306/channie_gym
    username: ${DB_USER_NAME} # root
    password: ${DB_PASSWORD} # root_password

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

jwt:
  secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: "test"
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

jwt:
  secret: testtesttesttesttesttesttesttesttesttesttesttest
