name: Backend CD Dev

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.jar

  download-and-deploy:
    name: Deploy to EC2
    runs-on: [self-hosted, dev]
    needs: build-and-upload

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: /tmp/deployment

      - name: Kill Application
        run: |
          lsof -ti:8080 | xargs -r kill -15
          sleep 5

      - name: Deploy Application
        run: |
          sleep 10
          sudo cp /tmp/deployment/*.jar /home/ubuntu/lv3-final-mission/

          cd /home/ubuntu/lv3-final-mission
          nohup java -jar *.jar > app.log 2>&1 &

          rm -rf /tmp/deployment
