name: Backend CD Prod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build and Upload JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.jar

  download-and-deploy:
    name: Deploy to EC2
    runs-on: [self-hosted, prod]
    needs: build-and-upload

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: /tmp/deployment


      - name: Copy JAR to server
        run: |
          sudo cp /tmp/deployment/*.jar /home/ubuntu/lv3-final-mission/
          rm -rf /tmp/deployment

      - name: Grant execute permission to deploy script
        run: sudo chmod +x /home/ubuntu/lv3-final-mission/deploy.sh

      - name: Execute Deploy Script
        run: |
          sudo /home/ubuntu/lv3-final-mission/deploy.sh